config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get '/users', to: 'devise/resgistrations#new'
    get '/users/password', to: 'devise/passwords#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users
  get 'home/about'
  get 'jobs/salaries'
  resources :jobs do
    collection do
      get 'search'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "jobs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/job.rb
class Job < ApplicationRecord

  validates :title, presence:true, length: { minimum:5, maximum:100}
  validates :company, presence:true, length: { minimum:5, maximum:100}
  validates :location, presence:true, length: { minimum:5, maximum:100}
  validates :description, presence:true, length: {minimum:10}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[ show edit update destroy ]

  # GET /jobs or /jobs.json
  # def index
  #   @jobs = Job.all
  # end
  def index
    if params[:search]
      @jobs = Job.where("title LIKE ?", "%#{params[:search]}%")
    else
      @jobs = Job.all
    end
  end
  # GET /jobs/1 or /jobs/1.json
  def show
  end
  
  def salaries
    @jobs = Job.all
  end


  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to job_url(@job), notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to job_url(@job), notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:title, :company, :location, :description, :salary)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/home/about.html.erb
<div class="about-h">
<h1>
Welcome to Careerly!
</h1>
</div>
<div class="about-c">
<br><br>
<h4>
At Careerly, we believe that finding the right career is a journey that deserves the best possible tools and resources. Our job search web application is designed to empower job seekers like you to navigate the ever-evolving job market with confidence and clarity.
<br><br>
Who We Are:
<br><br>
Careerly is a dedicated team of professionals who are passionate about helping individuals achieve their career aspirations. Our mission is to connect job seekers with opportunities that align with their skills, interests, and values. We understand the challenges you face in today's competitive job landscape, and we are committed to providing you with the support you need to succeed.
<br><br>
What We Offer:
<br><br>
1. Advanced Job Search: Our powerful job search engine employs cutting-edge technology to gather job listings from various sources, ensuring that you have access to the latest and most relevant opportunities in your chosen field.
<br><br>
2. Customized Job Recommendations: We know that every individual is unique, and so are their career preferences. Our intelligent algorithms analyze your profile, skills, and preferences to deliver personalized job recommendations that match your criteria.
<br><br>
3. Professional Development: Careerly isn't just about finding jobs; it's also about helping you grow as a professional. We offer a range of resources, including expert career advice, resume building tools, interview tips, and more, to enhance your skills and boost your chances of landing your dream job.
<br><br>
4. Company Insights: Making informed decisions is crucial when it comes to choosing the right employer. Our platform provides valuable insights into companies, their cultures, and employee experiences to help you make well-informed decisions about potential employers.
<br><br>
5. Community Support: We understand the importance of a strong support network during your job search. At Careerly, you'll have access to a vibrant community of like-minded individuals, where you can network, share experiences, and gain valuable insights from others in similar career paths.
<br><br>
Our Promise:
<br><br>
Your success is our success. We are committed to providing a user-friendly, secure, and efficient platform that streamlines your job search process and empowers you to take charge of your career journey. Whether you're a recent graduate, a seasoned professional, or someone exploring new opportunities, Careerly is here to guide you every step of the way.
<br><br>
Join us today, and let's embark on this exciting journey towards unlocking your full career potential together!
<br><br>
Remember, at Careerly, it's not just a job search; it's your career's best ally.
<br><br>
Get started now and supercharge your job search with Careerly!
</h4>
<br><br>
</div>

app/views/jobs/_form.html.erb
<br>
<div class="col-xl-4 col-md-6 col-sm-8 col-10" style="margin:auto; background-image: linear-gradient(to right, #ff9966, #ff5e62); border-radius: 6px; padding:15px; margin-top:20px;">

<%= form_with(model: job) do |form| %>
  
  <h1>Post a New Job</h1>

  <div>
  <% invalid = job.errors.include?(:title)%>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: "form-control" %>
    <% if invalid %>
    <p style="color:red;">
    <%= job.errors.full_messages_for(:title).join(" ,")%>
    </p>
    <%end%>
  </div>

  <div>
  <% invalid = job.errors.include?(:company)%>
    <%= form.label :company, style: "display: block" %>
    <%= form.text_field :company, class: "form-control" %>
    <% if invalid %>
    <p style="color:red;">
    <%= job.errors.full_messages_for(:company).join(" ,")%>
    </p>
    <%end%>
  </div>

  <div>
  <% invalid = job.errors.include?(:location)%>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location, class: "form-control" %>
    <% if invalid %>
    <p style="color:red;">
    <%= job.errors.full_messages_for(:location).join(" ,")%>
    </p>
    <%end%>
  </div>

  <div>
  <% invalid = job.errors.include?(:description)%>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description, class: "form-control" %>
    <% if invalid %>
    <p style="color:red;">
    <%= job.errors.full_messages_for(:description).join(" ,")%>
    </p>
    <%end%>
  </div>

  <div>
  <% invalid = job.errors.include?(:salary)%>
    <%= form.label :salary, style: "display: block" %>
    <%= form.number_field :salary, class: "form-control" %>
    <% if invalid %>
    <p style="color:red;">
    <%= job.errors.full_messages_for(:salary).join(" ,")%>
    </p>
    <%end%>
  </div>

  <div>
    <%= form.submit class:"btn btn-primary col-12"%>
  </div>
<% end %>
</div>

app/views/jobs/_job.html.erb
<div id="<%= dom_id job %>" class="job-container">
  <p>
    <strong><%= job.title %></strong>
    
  </p>

  <p>
    <strong><%= job.company %></strong>
    
  </p>

  <p>
    <strong><%= job.location %></strong>
    
  </p>

  <p>
    <strong>Description:</strong>
    <%= job.description %>
  </p>

  <p>
    <strong>Salary:</strong>
    <%= job.salary %>
  </p>
    <p>
      <%= link_to "", job, class:"job-link" %>
    </p>

</div>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render "form", job: @job %>

<br>

<div>
  <%= link_to "Show this job", @job %> |
  <%= link_to "Back to jobs", jobs_path %>
</div>

app/views/jobs/index.html.erb
<%= stylesheet_link_tag("job") %>
<h1>Jobs</h1>
<div class='search'>
<%= form_tag(jobs_path, method: "get") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search by title..." %>
  <%= submit_tag "Search" %>
<% end %>
</div>


<table>
  <!-- Table content -->
</table>
<p style="color: green"><%= notice %></p>
<div id="jobs" class="text-left" style="padding:10px;">
  <% @jobs.each do |job| %>
    <%= render job %>
  <% end %>
</div>

app/views/jobs/new.html.erb
<div class="row"><%= render "form", job: @job %></div>


<br>

app/views/jobs/salaries.html.erb
<h1>Job Titles and Salaries</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Salary</th>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.salary %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/jobs/search.html.erb
<h1>Search Results</h1>

<% if @jobs.any? %>
  <table>
    <!-- Table content -->
  </table>
<% else %>
  <p>No results found.</p>
<% end %>

app/views/jobs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @job %>

<div>
  <%= link_to "Edit this job", edit_job_path(@job) %> |
  <%= link_to "Back to jobs", jobs_path %>

  <%= button_to "Destroy this job", @job, method: :delete %>
</div>

app/views/layouts/_footer.html.erb
  <section class="">
  <!-- Footer -->
  <footer class="text-center text-black" style="background-image: linear-gradient(to right, #ff6e7f, #bfe9ff); position: fixed;
  bottom: 0;
  width: 100%;
  background-color: #333;
  color: #fff;
  text-align: center;
  padding: 10px 0;">
    <!-- Grid container -->
    

    <!-- Copyright -->
    <div class="text-center p-3" style="background-image: linear-gradient(to right, #ff6e7f, #bfe9ff);">
      © 2020 Copyright:
      <a class="text-black" href="https://vedavyas-portfolio.netlify.app/">Vedavyas Sai Anantahsetty</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
</section>
  

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-image: linear-gradient(to right, #ff6e7f, #bfe9ff); color:white;">
<%= link_to "Career.ly", home_about_path, class:"navbar-brand", style:"margin-left: 20px; color: white;" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent" style="margin-left: 20px;">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      <%= link_to "Explore jobs", root_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Salaries", jobs_salaries_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Create a job", new_job_path, class: "nav-link"%>
      </li>
      
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "Profile", edit_user_registration_path  , class: "nav-link"%>
      </li>
      <li>
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit" style="padding:0;"><%= link_to "Sign out", destroy_user_session_path, class: "nav-link"%> </button>
      </li>
      <% else %>
      <li>
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit" style="padding:0;"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link"%> </button>
      </li>
      <%end%>
    </ul>
    
    
        
      
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ror1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "layouts/navbar"%>
    <%= yield %>
  <%= render "layouts/footer"%>
  </body>
</html>